# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mpesa_client
from mpesa_client.models.o_auth_access_token_response import OAuthAccessTokenResponse  # noqa: E501
from mpesa_client.rest import ApiException


class TestOAuthAccessTokenResponse(unittest.TestCase):
    """OAuthAccessTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuthAccessTokenResponse(self):
        """Test OAuthAccessTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mpesa_client.models.o_auth_access_token_response.OAuthAccessTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
