# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mpesa_client
from mpesa_client.models.b2_c_payment_response import B2CPaymentResponse  # noqa: E501
from mpesa_client.rest import ApiException


class TestB2CPaymentResponse(unittest.TestCase):
    """B2CPaymentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testB2CPaymentResponse(self):
        """Test B2CPaymentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mpesa_client.models.b2_c_payment_response.B2CPaymentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
