# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mpesa_client
from mpesa_client.models.transaction_status_query_response import TransactionStatusQueryResponse  # noqa: E501
from mpesa_client.rest import ApiException


class TestTransactionStatusQueryResponse(unittest.TestCase):
    """TransactionStatusQueryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionStatusQueryResponse(self):
        """Test TransactionStatusQueryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mpesa_client.models.transaction_status_query_response.TransactionStatusQueryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
