# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mpesa_client
from mpesa_client.apis.experience_api import ExperienceApi  # noqa: E501
from mpesa_client.rest import ApiException


class TestExperienceApi(unittest.TestCase):
    """ExperienceApi unit test stubs"""

    def setUp(self):
        self.api = ExperienceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mpesa_accountbalance_v1_query_post(self):
        """Test case for mpesa_accountbalance_v1_query_post

        Make an Account Balance query  # noqa: E501
        """
        pass

    def test_mpesa_reversal_v1_request_post(self):
        """Test case for mpesa_reversal_v1_request_post

        Reverse an M-Pesa Transaction  # noqa: E501
        """
        pass

    def test_mpesa_stkpushquery_v1_query_post(self):
        """Test case for mpesa_stkpushquery_v1_query_post

        Query the status of a Lipa na M-Pesa Online Payment  # noqa: E501
        """
        pass

    def test_mpesa_transactionstatus_v1_query_post(self):
        """Test case for mpesa_transactionstatus_v1_query_post

        Query the Transaction Status of an M-Pesa Transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
