# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mpesa_client
from mpesa_client.apis.security_api import SecurityApi  # noqa: E501
from mpesa_client.rest import ApiException


class TestSecurityApi(unittest.TestCase):
    """SecurityApi unit test stubs"""

    def setUp(self):
        self.api = SecurityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_oauth_v1_generate_get(self):
        """Test case for oauth_v1_generate_get

        Generate an OAuth Access Token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
