# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mpesa_client
from mpesa_client.apis.payments_api import PaymentsApi  # noqa: E501
from mpesa_client.rest import ApiException


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self):
        self.api = PaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mpesa_b2b_v1_paymentrequest_post(self):
        """Test case for mpesa_b2b_v1_paymentrequest_post

        Make a B2B Payment Request  # noqa: E501
        """
        pass

    def test_mpesa_c2b_v1_registerurl_post(self):
        """Test case for mpesa_c2b_v1_registerurl_post

        Register C2B Confirmation and Validation URLs  # noqa: E501
        """
        pass

    def test_mpesa_c2b_v1_simulate_post(self):
        """Test case for mpesa_c2b_v1_simulate_post

        Simulate a C2B Payment  # noqa: E501
        """
        pass

    def test_mpesa_stkpush_v1_processrequest_post(self):
        """Test case for mpesa_stkpush_v1_processrequest_post

        Initiate a Lipa na M-Pesa Online Payment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
