# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mpesa_client
from mpesa_client.apis.disbursement_api import DisbursementApi  # noqa: E501
from mpesa_client.rest import ApiException


class TestDisbursementApi(unittest.TestCase):
    """DisbursementApi unit test stubs"""

    def setUp(self):
        self.api = DisbursementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mpesa_b2c_v1_paymentrequest_post(self):
        """Test case for mpesa_b2c_v1_paymentrequest_post

        Make a B2C Payment Request  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
