# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mpesa_client
from mpesa_client.models.stk_push_query_request import StkPushQueryRequest  # noqa: E501
from mpesa_client.rest import ApiException


class TestStkPushQueryRequest(unittest.TestCase):
    """StkPushQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStkPushQueryRequest(self):
        """Test StkPushQueryRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mpesa_client.models.stk_push_query_request.StkPushQueryRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
