# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mpesa_client
from mpesa_client.models.c2_b_payment_simulation_request import C2BPaymentSimulationRequest  # noqa: E501
from mpesa_client.rest import ApiException


class TestC2BPaymentSimulationRequest(unittest.TestCase):
    """C2BPaymentSimulationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testC2BPaymentSimulationRequest(self):
        """Test C2BPaymentSimulationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mpesa_client.models.c2_b_payment_simulation_request.C2BPaymentSimulationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
