# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mpesa_client
from mpesa_client.models.account_balance_query_request import AccountBalanceQueryRequest  # noqa: E501
from mpesa_client.rest import ApiException


class TestAccountBalanceQueryRequest(unittest.TestCase):
    """AccountBalanceQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountBalanceQueryRequest(self):
        """Test AccountBalanceQueryRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mpesa_client.models.account_balance_query_request.AccountBalanceQueryRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
