# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mpesa_client
from mpesa_client.models.b2_c_error_response import B2CErrorResponse  # noqa: E501
from mpesa_client.rest import ApiException


class TestB2CErrorResponse(unittest.TestCase):
    """B2CErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testB2CErrorResponse(self):
        """Test B2CErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mpesa_client.models.b2_c_error_response.B2CErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
