# coding: utf-8

"""
    Safaricom APIs

    # Introduction  What does your API do?  # Overview  Things that the developers should know about  # Authentication  What is the preferred way of using the API?  # Error Codes  What errors and status codes can a user expect?  # Rate limit  Is there a limit to the number of requests an user can send?  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "mpesa-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Safaricom APIs",
    author_email="",
    url="",
    keywords=["Swagger", "Safaricom APIs"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    # Introduction  What does your API do?  # Overview  Things that the developers should know about  # Authentication  What is the preferred way of using the API?  # Error Codes  What errors and status codes can a user expect?  # Rate limit  Is there a limit to the number of requests an user can send?  # noqa: E501
    """
)
