# coding: utf-8

"""
    Safaricom APIs

    M-Pesa API client for Daraja  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class C2BURLRegistrationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'originator_coversation_id': 'str',
        'response_code': 'str',
        'response_description': 'str'
    }

    attribute_map = {
        'originator_coversation_id': 'OriginatorCoversationID',
        'response_code': 'ResponseCode',
        'response_description': 'ResponseDescription'
    }

    def __init__(self, originator_coversation_id=None, response_code=None, response_description=None):  # noqa: E501
        """C2BURLRegistrationResponse - a model defined in Swagger"""  # noqa: E501
        self._originator_coversation_id = None
        self._response_code = None
        self._response_description = None
        self.discriminator = None
        if originator_coversation_id is not None:
            self.originator_coversation_id = originator_coversation_id
        if response_code is not None:
            self.response_code = response_code
        if response_description is not None:
            self.response_description = response_description

    @property
    def originator_coversation_id(self):
        """Gets the originator_coversation_id of this C2BURLRegistrationResponse.  # noqa: E501

        This is a global unique identifier for the transaction request returned by the API proxy upon successful request submission.  # noqa: E501

        :return: The originator_coversation_id of this C2BURLRegistrationResponse.  # noqa: E501
        :rtype: str
        """
        return self._originator_coversation_id

    @originator_coversation_id.setter
    def originator_coversation_id(self, originator_coversation_id):
        """Sets the originator_coversation_id of this C2BURLRegistrationResponse.

        This is a global unique identifier for the transaction request returned by the API proxy upon successful request submission.  # noqa: E501

        :param originator_coversation_id: The originator_coversation_id of this C2BURLRegistrationResponse.  # noqa: E501
        :type: str
        """

        self._originator_coversation_id = originator_coversation_id

    @property
    def response_code(self):
        """Gets the response_code of this C2BURLRegistrationResponse.  # noqa: E501

        It indicates whether Mobile Money accepts the request or not.  # noqa: E501

        :return: The response_code of this C2BURLRegistrationResponse.  # noqa: E501
        :rtype: str
        """
        return self._response_code

    @response_code.setter
    def response_code(self, response_code):
        """Sets the response_code of this C2BURLRegistrationResponse.

        It indicates whether Mobile Money accepts the request or not.  # noqa: E501

        :param response_code: The response_code of this C2BURLRegistrationResponse.  # noqa: E501
        :type: str
        """

        self._response_code = response_code

    @property
    def response_description(self):
        """Gets the response_description of this C2BURLRegistrationResponse.  # noqa: E501

        This is the status of the request.  # noqa: E501

        :return: The response_description of this C2BURLRegistrationResponse.  # noqa: E501
        :rtype: str
        """
        return self._response_description

    @response_description.setter
    def response_description(self, response_description):
        """Sets the response_description of this C2BURLRegistrationResponse.

        This is the status of the request.  # noqa: E501

        :param response_description: The response_description of this C2BURLRegistrationResponse.  # noqa: E501
        :type: str
        """

        self._response_description = response_description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(C2BURLRegistrationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, C2BURLRegistrationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
